# Generated by Django 2.2.3 on 2019-07-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.TextField(default='default name'),
            preserve_default=False,
        ),
    ]
